version: "3"
services:
  pythonflaskapp:
    image: mohammadmualla/pythonflaskapp:v1.0
    container_name: pythonflaskapp
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: 'mysql'
      DB_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_DB: 'statisticsDB'
      MYSQL_PASSWORD: 'root'
    depends_on:
      - mysql

  mysql:
    image: mohammadmualla/mysqldb
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'statisticsDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
